### PR TITLE
Added support for Compass.

### PR DESCRIPTION
**Pull request by parkr**
Added support for compass.

Tested in my sample project.

### CODE REVIEW

**Comment by ahamid** [comment]
Parker, thanks for the contributions! We'll review them for merging soon.

**Comment by mkuklis** [comment]
@parkr I've been thinking a little bit more about it and I think I would like to avoid putting more dependencies in. I'm afraid there are a lot of different options for css/js frameworks and we will never be able to make everybody happy. I think the better approach is to just keep it minimal and let people customize their project (like you did in this pull request) after init. Let me know your thoughts.

**Comment by parkr** [comment]
@mkuklis That sounds very reasonable. What do you think about adding it to the grunt file as a command, but not adding it to the `watch` command?

**Comment by ahamid** [comment]
Hey Parker, will the following work for you as a compromise?

https://github.com/incandescent/mbt/pull/6

This allows user-defined config which will allow you to implement compass without requiring explicit support in the core project grunt.js file.  We just spiked this, so LMK what you think.

**Comment by parkr** [comment]
Looks great!!

**Comment by parkr** [comment]
Maybe offer some samples in the file? You can name them so that they aren't imported, but to give some samples (compass, sass, etc) as `cfg/[name].json.sample` files or something would be awesome.

**Pull request closed without merging**
